### ISSUE TITLE
"Depend On" when start server

### ISSUE THREAD

**Issue by hukacode** [ErnestOrt/Trampoline#31]
Hi, guys

I have a "config-server", my other services need to run after that "config-server". Can you show me how to set delay time?
Thank you for your efforts. It's very helpful for me.

**Comment by ErnestOrt** [comment]
Hi @hukacode!

Thanks for your feedback.

Right now you can first, start "config-server" and when it will be up&running, start your other services as a group.

We will work to analyse it, and we will be back to you when it will be implemented.

Cheers!

**Comment by hukacode** [comment]
Hi, @ErnestOrt!

I got it.
Thank you so much for your very very fast response,

By the way, I had a few Java experience. What if your team define some small tasks, I'm happy to help.

Best regards,
Huka.

**Comment by ErnestOrt** [comment]
Sure @hukacode, you're really welcomed to join Trampoline.

The most important task we need now is Trampoline's promotion in order to increase community and users around it. So, I encourage you to tweet or comment about it on any website or even talk about Trampoline to your colleagues and friends.

Regarding code, do you feel you can implement feature you have proposed? if so, the only thing that you have to do is a Pull Request and later on a Merge Request.

We can exchange some emails in order to analyze it properly before you start!

If so, send me an email and we will be able to start.

Regards,
Ernest

**Comment by hukacode** [comment]
Hi, @ErnestOrt

My email is hungnlk@hukacode.com.
However, I don't have any ideal about my issue. I try to run **gradle bootRun "config-server" & gradle bootRun ...**, but the first statement is not completed (80% Executing,...). I thought about delay time, but it is not a good solution.
Maybe I can watch and fix some small issues.

**Comment by ErnestOrt** [comment]
Solved on Release 3.16.

@hukacode Thanks for your feedback
