### ISSUE TITLE
Add endpoint for gracefully shutting Trampoline down

### ISSUE THREAD

**Issue by JTWalraven** [ErnestOrt/Trampoline#38]
It would be great to have a way to shut Trampoline down from inside of the application just as you would other instances. @ErnestOrt I am curious for your thoughts on this. Do you think we could treat Trampoline as a microservice within the instance list, or do you think it would be better to make a separate shutdown endpoint?

**Comment by ErnestOrt** [comment]
Sounds good @JTWalraven ! At the end this projects aims to reduce time spent in front of a terminal and you have to go there to stop it :))

PR #41 

I create this Pull Request so if you were imagine some better implementation speak up, otherwise I am going to close it,

While doing it, I was wondering if it would be necessary to stop all started ms or even if it would be better to have a "hard or soft shutdown":
* Hard: stop Trampoline + ms
* Soft: stop only Trampoline

What do you think?

**Comment by JTWalraven** [comment]
I am checking it out now.

**Comment by JTWalraven** [comment]
I think it would be better to have a soft shutdown. That would keep a more loosely coupled architecture and make Trampoline treated similarly to the other microservices.

Maybe we could open an issue for discussing a method of quickly shutting all instances down?

**Comment by ErnestOrt** [comment]
Sure! Let's do that.
